### PR TITLE
Use Rollup emitFile instead of fs.writeFile

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
This PR is the same as #71 but recreated for the current v3 branch.

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
@thgh any chance you can look at this PR?

**Comment by thgh** [comment]
OK, will merge this

**Review by thgh — APPROVED** [review]

**Comment by thgh** [comment]
The tests didn't pass so I refactored the naming and aligned it with rollup-plugin-css-only. The options now also align with the Rollup emitFile API: `name` and `fileName`. I'm not sure what they do exactly, but I tried to describe it in comments, let me know if that is inaccurate!

Released v4.0.0 because not sure if it's a breaking change

**Comment by nielsvanvelzen** [comment]
I didn't set the output variable before so for me the change was breaking. I had to add the `fileName` property and set it to `projectname.css` to get it in the same location as before. Everything is working now.

Thanks for the merge!

**Comment by thgh** [comment]
Good to hear it's working 🎉 

Slightly unfortunate that Rollup defaults to generating unpredictable filenames. On the other, I hope it's a good longterm decision that this plugin requires explicit naming for predictable filenames.

**Pull request merged**
